### ISSUE TITLE
Add support for Client side field level encryption

### ISSUE THREAD

**Issue by HeinrichGrobler** [theogravity/migrate-mongo-alt#3]
There is currently no support for Client Side Field Level Encryption (CLSFE) because the package is missing the mongodb-client-encryption package which is a dependency for CSFLE to work

Describe the solution you'd like

The solution to the problem is adding the package mentioned above which enables the CLSFE. I do not believe that there is anything else missing as the additional configuration can be passed using the existing config file by the consumer of the package.

![image](https://user-images.githubusercontent.com/62885638/212281028-e1de536e-ddac-4479-8778-ce5a9f540ec2.png)

![image](https://user-images.githubusercontent.com/62885638/212281082-9471d4de-216e-4891-a6d0-9b271d250554.png)

CSFLE setup is based on this [article](https://www.mongodb.com/developer/languages/javascript/client-side-field-level-encryption-csfle-mongodb-node/)

**Comment by theogravity** [comment]
The latest version of `migrate-mongo-alt` no longer has `mongodb` as a direct dep, and is a peer dep instead. You should be able to install `mongodb` and the CSFL package directly in your own package to get what you need.
